
pytest_xfail plugin
===================

mark python tests as expected-to-fail and report them separately.

.. contents::
  :local:

usage
------------

Use the generic mark decorator to add the 'xfail' keyword to your 
test function::

    @py.test.mark.xfail
    def test_hello():
        ...

This test will be executed but no traceback will be reported 
when it fails. Instead terminal reporting will list it in the 
"expected to fail" section or "unexpectedly passing" section.

Start improving this plugin in 30 seconds
=========================================


Do you find the above documentation or the plugin itself lacking? 

1. Download `pytest_xfail.py`_ plugin source code 
2. put it somewhere as ``pytest_xfail.py`` into your import path 
3. a subsequent ``py.test`` run will use your local version

Further information: extend_ documentation, other plugins_ or contact_.  

.. _`pytest_xfail.py`: http://bitbucket.org/hpk42/py-trunk/raw/85fe614ab05f301f206935d11a477df184cbbce6/py/test/plugin/pytest_xfail.py
.. _`extend`: ../extend.html
.. _`plugins`: index.html
.. _`contact`: ../../contact.html
.. _`checkout the py.test development version`: ../../download.html#checkout
